import React, { useState } from 'react';
import { Binary, Eye, FileSpreadsheet, Copy, Check, Terminal, FileDown } from 'lucide-react';
import { Card } from '../ui/Card.jsx';
import { Badge } from '../ui/Badge.jsx';
import { Button } from '../ui/Button.jsx';
import { DownloadBtn } from './DownloadBtn.jsx';
import { downloadBlob, formatBytes } from '../../core/fileUtils.js';

export function CompressPanel({ encodedBitString, packedBlob, fileMeta, stats, codeTable }) {
  const [showFull, setShowFull] = useState(false);
  const [copiedBits, setCopiedBits] = useState(false);

  const bitPreview = showFull 
    ? encodedBitString 
    : (encodedBitString.slice(0, 400) + (encodedBitString.length > 400 ? '...' : ''));

  const handleCopyBits = () => {
    navigator.clipboard.writeText(encodedBitString);
    setCopiedBits(true);
    setTimeout(() => setCopiedBits(false), 2000);
  };

  const handleDownloadReport = () => {
    const reportText = `=====================================================
HUFFPRESS — HUFFMAN COMPRESSION REPORT
=====================================================
File Name:            ${fileMeta.name}
Original File Size:   ${formatBytes(stats.originalBytes)} (${stats.originalBits.toLocaleString()} bits)
Compressed File Size: ${formatBytes(stats.totalCompressedBytes)} (${stats.compressedBits.toLocaleString()} payload bits)
Compression Ratio:    ${stats.compressionRatio}
Space Saved:          ${stats.fileSavingsPercent}%
Shannon Entropy:      ${stats.entropy} bits/symbol
Unique Characters:    ${stats.uniqueCharsCount}
Original SHA-256:     ${fileMeta.sha256}
Generated On:         ${new Date().toISOString()}

HUFFMAN CODE TABLE:
-----------------------------------------------------
${Object.entries(codeTable).map(([c, code]) => `${JSON.stringify(c).padEnd(12)} -> ${code} (${code.length} bits)`).join('\n')}

=====================================================
Generated by HuffPress Engine (DSA Mini Project)
=====================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    downloadBlob(blob, `${fileMeta.name}_compression_report.txt`);
  };

  return (
    <Card
      title="Compressed Bitstream & Binary Output"
      subtitle="The continuous stream of variable-length prefix bits ready for storage"
      icon={Binary}
      headerAction={
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopyBits}
            icon={copiedBits ? Check : Copy}
          >
            {copiedBits ? 'Copied Bits' : 'Copy Bitstream'}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadReport}
            icon={FileDown}
          >
            Export Report
          </Button>
        </div>
      }
    >
      <div className="space-y-4">
        {/* Bitstream Preview Terminal */}
        <div className="p-4 rounded-xl bg-[#09090E] border border-[#222234] font-mono text-xs text-emerald-400 break-all leading-relaxed max-h-48 overflow-y-auto select-all shadow-inner">
          {bitPreview || 'No bitstream generated.'}
        </div>

        {/* Action row & Bitstream length note */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pt-2">
          <div className="flex items-center gap-3">
            <span className="text-xs font-mono text-slate-400">
              Total: <strong className="text-white">{encodedBitString.length.toLocaleString()} bits</strong> ({Math.ceil(encodedBitString.length / 8)} packed bytes)
            </span>
            {encodedBitString.length > 400 && (
              <button
                onClick={() => setShowFull(!showFull)}
                className="text-xs font-mono text-purple-400 hover:text-purple-300 underline underline-offset-2"
              >
                {showFull ? 'Show Truncated' : 'Show Full Bitstream'}
              </button>
            )}
          </div>

          <DownloadBtn
            packedBlob={packedBlob}
            fileMeta={fileMeta}
            stats={stats}
          />
        </div>
      </div>
    </Card>
  );
}
